require 'omf-aggmgr/ogs_wimaxrf/bspbase'

class UnexposedParams < BSPBase
   @name='unexpose'
   @categoryName = 'all' 
   @info='Unexposed parameters'
   param :bsid, :bsname => 'bsid', :name => '[bsid]', :help => 'Base station ID (0x4451DB000000)'
   param :authid, :bsname => 'authgw_id', :name => '[authid]', :help => 'Authentication gateway identifier (0x41534E4757303030)'
   param :authip, :bsname => 'authgw_ip', :name => '[authip]', :help => 'Authentication gateway IP (0x0A030047)'
   param :authport, :bsname => 'authgw_port', :name => '[authport]', :help => 'Authentication gateway port [0x0000 - 0xFFFF] (0x08B7)'
   param :gwid, :bsname => 'asngw_id', :name => '[gwid]', :help => 'ASN Gateway identifier (0x41534E4757303030)'
   param :gwdpip, :bsname => 'asngw_dp_ip', :name => '[gwdpip]', :help => 'ASN gateway datapath controller IP address in hex (0x0A030047)'
   param :gwdpport, :bsname => 'asngw_dp_port', :name => '[gwdpport]', :help => 'ASN gateway datapath controller port [0x0000 - 0xFFFF]  (0x08B7)'
   param :gwepip, :bsname => 'asngw_ep_ip', :name => '[asnGatewayEPathIp]', :help => 'ASN gateway epath IP (0x0A030047)'
   param :gwepport, :bsname => 'asngw_ep_port', :name => '[asnGatewayEPathPort]', :help => 'ASN gateway epath port [0x0000 - 0xFFFF]  (0x08B7)'
   param :bsrxport, :bsname => 'bs_rx_port', :name => '[bsrxport]', :help => 'ASN gateway  receive port [0x0000 - 0xFFFF]  (0x08B7)'
   param :debug1, :bsname => 'dbg_data1', :name => '[debug1]', :help => 'Debug variable 1 (0x00000000)'
   param :debug2, :bsname => 'dbg_data2', :name => '[debug2]', :help => 'Debug variable 2 (0x00000001)'
   param :debug3, :bsname => 'dbg_data3', :name => '[debug3]', :help => 'Debug variable 3 (0x0000000A)'
   param :debug4, :bsname => 'dbg_data4', :name => '[debug4]', :help => 'Debug variable 4 (0x00000000)'
   param :debug5, :bsname => 'dbg_data5', :name => '[debug5]', :help => 'Debug variable 5 (0x00000000)'
   param :debug6, :bsname => 'dbg_data6', :name => '[debug6]', :help => 'Debug variable 6 (0x00000000)'
   param :debug7, :bsname => 'dbg_data7', :name => '[debug7]', :help => 'Debug variable 7 (0x00000028)'
   param :debug8, :bsname => 'dbg_data8', :name => '[debug8]', :help => 'Debug variable 8 (0x00000105)'
   param :debug9, :bsname => 'dbg_data9', :name => '[debug9]', :help => 'Debug variable 9 (0x00000000)'
   param :debug10, :bsname => 'dbg_data10', :name => '[debug10]', :help => 'Debug variable 10 (0x00000000)'
   param :debug11, :bsname => 'dbg_data11', :name => '[debug11]', :help => 'Debug variable 11 (0x00000000)'
   param :debug12, :bsname => 'dbg_data12', :name => '[debug12]', :help => 'Debug variable 12 (0x00000046)'
   param :debug13, :bsname => 'dbg_data13', :name => '[debug13]', :help => 'Debug variable 13 (0x00000000)'
   param :debug14, :bsname => 'dbg_data14', :name => '[debug14]', :help => 'Debug variable 14 (0x00000000)'
   param :debug15, :bsname => 'dbg_data15', :name => '[debug15]', :help => 'Debug variable 15 (0x00000000)'
   param :debug16, :bsname => 'dbg_data16', :name => '[debug16]', :help => 'Debug variable 16 (0x00000005)'
   param :debug17, :bsname => 'dbg_data17', :name => '[debug17]', :help => 'Debug variable 17 (0)'
   param :debug18, :bsname => 'dbg_data18', :name => '[debug18]', :help => 'Debug variable 18 (0)'
   param :debug19, :bsname => 'dbg_data19', :name => '[debug19]', :help => 'Debug variable 19 (0)'
   param :debug20, :bsname => 'dbg_data20', :name => '[debug20]', :help => 'Debug variable 20 (0)'
   param :debug21, :bsname => 'dbg_data21', :name => '[debug21]', :help => 'Debug variable 21 (0)'
   param :debug22, :bsname => 'dbg_data22', :name => '[debug22]', :help => 'Debug variable 22 (0)'
   param :debug23, :bsname => 'dbg_data23', :name => '[debug23]', :help => 'Debug variable 23 (1)'
   param :debug24, :bsname => 'dbg_data24', :name => '[debug24]', :help => 'Debug variable 24 (0)'
   param :debug25, :bsname => 'dbg_data25', :name => '[debug25]', :help => 'Debug variable 25 (1)'
   param :debug26, :bsname => 'dbg_data26', :name => '[debug26]', :help => 'Debug variable 26 (65552)'
   param :debug28, :bsname => 'dbg_data28', :name => '[debug28]', :help => 'Debug variable 28 (1)'
   param :debug29, :bsname => 'dbg_data29', :name => '[debug29]', :help => 'Debug variable 29 (0)'
   param :debug30, :bsname => 'dbg_data30', :name => '[debug30]', :help => 'Debug variable 30 (3)'
   param :debug31, :bsname => 'dbg_data31', :name => '[debug31]', :help => 'Debug variable 31 (0)'
   param :debug32, :bsname => 'dbg_data32', :name => '[debug32]', :help => 'Debug variable 32 (0)'
end


class ArqService < BSPBase
   @name='arq'
   @categoryName ='arq'
   @info='Set ARQ parameters'
   param :enable, :bsname => 'arq', :name => '[enable]', :type => 'binary', :help => 'Enable ARQ: true/false (false)'
   param :wsize, :bsname => 'arq_window_size', :name => '[wsize]', :help => 'ARQ window size [0..1024] (1024)'
   param :rtmotx, :bsname => 'arq_retry_timeout_tx', :name => '[rtmotx]', :help => 'TX retry timeout [] (1000)'
   param :rtmorx, :bsname => 'arq_retry_timeout_rx', :name => '[rtmorx]', :help => 'RX retry timeout [] (1000)'
   param :blockltm, :bsname => 'arq_block_lifetime', :name => '[blockltm]', :help => 'ARQ block lifetime [] (5000)'
   param :sltmo,:bsname => 'arq_syncloss_timeout', :name => '[sltmo]', :help => 'Sync loss timeout [] (10000)'
   param :dlvrorder,:bsname=> 'arq_deliver_in_order', :name => '[dlvrorder]', :type => 'binary', :help => 'Delivery in order: true/false (true)'
   param :rxpurgetmo,:bsname => 'arq_rx_purge_timeout', :name => '[rxpurgetmo]', :help => 'RX purge timeout [] (5000)'
   param :bloksize,:bsname => 'arq_block_size', :name => '[blocksize]', :help => 'ARQ block size [0..(ARQ windows size/2)] (256)'
   param :ackproctime,:bsname => 'arq_ack_proc_time', :name => '[ackproctime]', :help => 'ACK proc time [] (0)'
   param :txackdelay,:bsname => 'arq_txack_delay', :name => '[txackdelay]', :help => 'Tx ACK delay [] (100)'
end

class HarqService < BSPBase
   @name='harq'
   @categoryName = 'harq'
   @info='Set HARQ parameters'
   param :pdusn, :bsname => 'harq_pdusn', :name => '[pdusn]', :type => 'binary', :help => 'PDU SN extended subheader reordering enabled: true/false (true)'
   param :enable, :bsname => 'harq', :name => '[enable]', :type => 'binary', :help => 'Enable HARQ: true/false (false)'
   param :mret, :bsname => 'max_retransmission', :name => '[retran]', :help => 'Maximum number of retransmissions [0..255] (4)'
   param :burst, :bsname => 'harq_max_no_of_burst', :name => '[burst]', :help => 'Maximum number of HARQ bursts per frame [0..255] (17)'
   param :uldelay, :bsname => 'harq_ack_delay_ul', :name => '[uldelay]', :help => 'Frame offset of UL ACK delay wrt to UL Burst [2,3] (3)'
   param :dldelay, :bsname => 'harq_ack_delay_dl', :name => '[dldelay]', :help => 'Frame offset of DL ACK delay wrt to DL Burst [1,2,3] (1)'
   param :mimoul,:bsname => 'mimo_ul_harq', :name => '[mimoul]', :type => 'binary', :help => 'MIMO HARQ support: true/false (IGNORED - mimo support not available for this BS)'
#  param :chase, :bsname => 'harq_chase_capability', :name => '[chase]', :help => 'HARQ Chase Capabilities' 
end

class AsngwService < BSPBase
  @name='asngw'
  @categoryName = 'asngw'
  @info='Set ASNGW parameters'
  param :rettimeout, :bsname => 'retransmit_timeout', :name => '[rettimeout]', :help => 'Retransmission timeout for each control packet (2)'
  param :retretry, :bsname => 'retransmit_retry', :name => '[retretry]', :help => 'Number of control packet retransmissions (3)'
end

class MonitorService < BSPBase
   @name='monitor'
   @categoryName='monitor' 
   @info='Set MONITOR parameters'
   param :msgmax, :bsname => 'msgmon_max', :name => '[msgmax]', :help => 'Maximum monitoring data size. (0x0080)'
   param :msgfile, :bsname => 'msgmon_file', :name => '[msgfile]', :help => 'Monitoring data type for local file monitoring (0x00)'
   param :msgfilt, :bsname => 'msgmon_filter', :name => '[msgfilt]', :help => 'Management message type to filter (0x43)'
end

class MaintenanceService < BSPBase
   @name='maintenance'
   @categoryName='mntapp'
   @info='Set MAINTENANCE parameters'
   param :alarmrst, :bsname => 'alarm_reset', :name => '[alarmrst]', :help => 'Alarm reset mode (0x01)'
   param :logseverity, :bsname => 'log_severity', :name => '[logseverity]', :help => 'Define event log level. (5)'
   param :rssilow, :bsname => 'rssi_low', :name => '[rssilow]', :help => 'Low threshold for generating the RSSI alarm (-440)'
   param :rssihigh, :bsname => 'rssi_high', :name => '[rssihigh]', :help => 'High threshold for generating the RSSI alarm (-200)'
   param :logicbsid, :bsname => 'logical_bsid', :name => '[logicbsid]', :help => 'Base Station ID (0x00000000)'
   param :templow, :bsname => 'temp_low', :name => '[templow]', :help => '@@@Text for temp_low@@@ (-5)'
   param :templowrestore, :bsname => 'temp_low_restore', :name => '[templowrestore]', :help => '@@@Text for temp_low_restore@@@ (0)'
   param :temphigh, :bsname => 'temp_high', :name => '[temphigh]', :help => '@@@Text for temp_high@@@ (70)'
   param :temphirestore, :bsname => 'temp_high_restore', :name => '[temphirestore]', :help => '@@@Text for temp_high_restore@@@ (62)'
end

class DriverBaseService < BSPBase
   @name='driver'
   @categoryName='driver'
   @info='Set DRIVER BASE parameters'
   param :fragmt, :bsname => 'fragment', :name => '[fragmt]', :help => 'Fragmenting on/off (0)'
   param :pack, :bsname => 'packing', :name => '[pack]', :help => 'Enable packing mode (0)'
   param :crc, :bsname => 'crc', :name => '[crc]', :help => 'Enable crc mode (1)'
   param :maxClients, :bsname => 'max_entry', :name => '[maxClients]', :help => 'Max number of clients (96)'
   param :blockadmin, :bsname => 'block_admin', :name => '[blockadmin]', :help => 'Block admin on/off (0)'
   param :carrieradmin, :bsname => 'carrier_admin', :name => '[carrieradmin]', :help => 'Carrier admin on/off (1)'
   param :maxservflow, :bsname => 'max_serviceflow', :name => '[maxservflow]', :help => 'Maxnumber of service flow (600)'
end

class DLProfileService < BSPBase
   CONVERSION = lambda {|x| (a = x.match(/\(\d*\)/)) == nil ? nil : a.to_a.last.chop.slice(1..3)}
   @name='dlprofile'
   @categoryName = 'wireless'
   @info='Set down link modulation scheme'
   param :dlprof1, :bsname => 'dl_profile1', :name => '[dlprof1]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (QPSK (CTC) 1/2 (13))'
   param :dlprof2, :bsname => 'dl_profile2', :name => '[dlprof2]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (QPSK (CTC) 3/4 (15))'
   param :dlprof3, :bsname => 'dl_profile3', :name => '[dlprof3]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (16-QAM (CTC) 1/2 (16))'
   param :dlprof4, :bsname => 'dl_profile4', :name => '[dlprof4]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (16-QAM (CTC) 3/4 (17))'
   param :dlprof5, :bsname => 'dl_profile5', :name => '[dlprof5]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (64-QAM (CTC) 1/2 (18))'
   param :dlprof6, :bsname => 'dl_profile6', :name => '[dlprof6]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (64-QAM (CTC) 2/3 (19))'
   param :dlprof7, :bsname => 'dl_profile7', :name => '[dlprof7]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (64-QAM (CTC) 3/4 (20))'
   param :dlprof8, :bsname => 'dl_profile8', :name => '[dlprof8]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (64-QAM (CTC) 5/6 (21))'
   param :dlprof9, :bsname => 'dl_profile9', :name => '[dlprof9]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => ' DL FEC code and modulation type of each burst profile on DCD message. (No Modulation (255))'
   param :dlprof10, :bsname => 'dl_profile10', :name => '[dlprof10]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (No Modulation (255))'
   param :dlprof11, :bsname => 'dl_profile11', :name => '[dlprof11]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (No Modulation (255))'
   param :dlprof12, :bsname => 'dl_profile12', :name => '[dlprof12]', :type => 'integer', :conversion =>'DLProfileService::CONVERSION', :help => 'DL FEC code and modulation type of each burst profile on DCD message. (No Modulation (255))'
end

class ULProfileService < BSPBase
   CONVERSION = lambda {|x| (a = x.match(/\(\d*\)/)) == nil ? nil : a.to_a.last.chop.slice(1..3)}
   @name='ulprofile'
   @categoryName = 'wireless'
   @info='Set up link modulation scheme'
   param :ulprof1, :bsname => 'ul_profile1', :name => '[ulprof1]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (QPSK (CTC) 1/2 (13))'
   param :ulprof2, :bsname => 'ul_profile2', :name => '[ulprof2]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (QPSK (CTC) 3/4 (15))'
   param :ulprof3, :bsname => 'ul_profile3', :name => '[ulprof3]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (16-QAM (CTC) 1/2 (16))'
   param :ulprof4, :bsname => 'ul_profile4', :name => '[ulprof4]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (16-QAM (CTC) 3/4 (17))'
   param :ulprof5, :bsname => 'ul_profile5', :name => '[ulprof5]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (No Modulation (255))'
   param :ulprof6, :bsname => 'ul_profile6', :name => '[ulprof6]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (No Modulation (255))'
   param :ulprof7, :bsname => 'ul_profile7', :name => '[ulprof7]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (No Modulation (255))'
   param :ulprof8, :bsname => 'ul_profile8', :name => '[ulprof8]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (No Modulation (255))'
   param :ulprof9, :bsname => 'ul_profile9', :name => '[ulprof9]', :type => 'integer', :conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (No Modulation (255))'
   param :ulprof10, :bsname => 'ul_profile10', :name => '[ulprof10]', :type => 'integer',:conversion =>'ULProfileService::CONVERSION', :help => 'UL FEC code and modulation type of each burst profile on UCD message. (No Modulation (255))'
end

class WirelessService < BSPBase
   @name='wireless'
   @categoryName = 'wireless'
   @info='Set WIRELESS parameters'
   param :dcducdinterv, :bsname => 'dcducd_interval', :name => '[dcducdinterv]', :help => 'Time interval between UCD and DCD mesages (units: frames) [10..4000] (0x00C8)'
   param :freq, :bsname => 'frequency', :name => '[freq]', :help => 'Center frequency (2590000)'
   param :bstxpow, :bsname => 'bs_tx_power', :name => '[bstxpow]', :help => 'BS transmit power (40)'
   param :bstxpowoffs, :bsname => 'bs_tx_power_offset', :name => '[bstxpowoffs]', :help => 'BS transmit power offset (0)'
   param :maxrxpow, :bsname => 'max_rx_power', :name => '[maxrxpow]', :help => 'Maximum rx power (-45)'
   param :bsrxgain, :bsname => 'bs_rx_gain', :name => '[bsrxgain]', :help => 'Bs rx gain (61)'
   param :antennagain, :bsname => 'antenna_gain', :name => '[antennagain]', :help => 'Antenna gain of BS (units: DBi) [0..255] (0)'
   param :permbase, :bsname => 'perm_base', :name => '[permbase]', :help => 'Permutation base (0x00)'
   param :bwmode, :bsname => 'bw_mode', :name => '[bwmode]', :help => 'Bandwidth mode [0 = 10MHz, 1=7MHz, 2=5MHz] (0)'
   param :dlulratio, :bsname => 'dlul_ratio', :name => '[dlulratio]', :help => '@@@Text for dlulration@@@ (0x00)'
   param :permutation, :bsname => 'permutation', :name => '[permutation]', :help => 'Support permutation mode. (0)'
   param :dlpermfusc, :bsname => 'dlperm_fusc', :name => '[dlpermfusc]', :help => 'DL permutation base for 2nd zone. [0..31] (0)'
   param :prbsid, :bsname => 'prbs_id', :name => '[prbsid]', :help => 'PRBS_ID for 2nd zone [0..2] (0)'
   param :preambleid, :bsname => 'preamble_id', :name => '[preambleid]', :help => 'Preamble number. Set different nunber for each BS and Segment from each other. The cell ID / segment # is derived from this parameter.[0..113] (0)'
   param :segment, :bsname => 'segment', :name => '[segment]', :help => 'Segment on/off (0)'
   param :segmentul, :bsname => 'segment_ul', :name => '[segmentul]', :help => ' (0)'
   param :usedsubchdl, :bsname => 'used_subch_dl', :name => '[usedsubchdl]', :help => 'Used DL subchannel group. (0x3F)'
   param :usedsubchul, :bsname => 'used_subch_ul', :name => '[usedsubchul]', :help => 'Used UL subchannel group. (0x0000000007FFFFFFFF)'
   param :numofsegment, :bsname => 'num_of_segment', :name => '[numofsegment]', :help => 'Number of segments (0)'
   param :compressmap, :bsname => 'compressed_map', :name => '[compressmap]', :help => 'Compressed map on/off (0)'
   param :dlmapencodetype, :bsname => 'dlmap_encode_type', :name => '[dlmapencodetype]', :help => 'Encoding-type of DL map (0)'
   param :dlmaprepcnt, :bsname => 'dlmap_repetition_cnt', :name => '[dlmaprepcnt]', :help => '@@@Text for dlmap_repetition_cnt@@@ (6)'
   param :dcducdrepcnt, :bsname => 'dcducd_repetition_cnt', :name => '[dcducdrepcnt]', :help => '@@@Text for dcducd_repetition_cnt@@@ (6)'
   param :multicastrepcnt, :bsname => 'multicast_repetition_cnt', :name => '[multicastrepcnt]', :help => '@@@Text for multicast_repetition_cnt@@@ (6)'
   param :admissionthres, :bsname => 'admission_threshold', :name => '[admissionthres]', :help => '@@@Text for admission_threshold@@@ (0)'
   param :minphyrateugs, :bsname => 'min_phy_rate_ugs', :name => '[minphyrateugs]', :help => 'Minimum PHY rate for Unsolicited Grant Service (QPSK 1/2 (0))'
   param :minphyrateertps, :bsname => 'min_phy_rate_ertps', :name => '[minphyrateertps]', :help => 'Minimum PHY rate for Extended Real-Time Polling Service (QPSK 1/2 (0))'
   param :minphyratertps, :bsname => 'min_phy_rate_rtps', :name => '[minphyratertps]', :help => 'Minimum PHY rate for Real-Time Polling Service (QPSK 1/2 (0))'
   param :minphyratenrtps, :bsname => 'min_phy_rate_nrtps', :name => '[minphyratenrtps]', :help => 'Minimum PHY rate for Non-Real-Time Polling Service. (QPSK 1/2 (0))'
   param :minphyratebe, :bsname => 'min_phy_rate_be', :name => '[minphyratebe]', :help => '@@@Text for min_phy_rate_be@@@ (QPSK 1/2 (0))'
   param :rangbackoffstart, :bsname => 'rang_backoff_start', :name => '[rangbackoffstart]', :help => 'Initial backoff window size for initial ranging contention, expressed as a power of 2. This is encoded in the UCD message in the MAC layer. [0..15] (3)'
   param :rangbackoffend, :bsname => 'rang_backoff_end', :name => '[rangbackoffend]', :help => 'Final backoff window size for initial ranging contention, expressed as a power of 2. This is encoded in the UCD message in the MAC layer. [0..15] (15)'
   param :reqbackoffstart, :bsname => 'req_backoff_start', :name => '[reqbackoffstart]', :help => 'Initial backoff window size for contention bandwidth requests, expressed as a power of 2. This is encoded in the UCD message in the MAC layer. [0..15] (3)'
   param :reqbackoffend, :bsname => 'req_backoff_end', :name => '[reqbackoffend]', :help => 'Final backoff window size for contention bandwidth requests, expressed as a power of 2. This is encoded in the UCD message in the MAC layer. [0..15] (15)'
   param :hobackoffstart, :bsname => 'ho_backoff_start', :name => '[hobackoffstart]', :help => 'Initial backoff window size for handoff. (3)'
   param :hobackoffend, :bsname => 'ho_backoff_end', :name => '[hobackoffend]', :help => 'Final bakoff window size for handoff. (15)'
   param :periodicbackoffstart, :bsname => 'periodic_backoff_start', :name => '[periodicbackoffstart]', :help => '@@@Text for periodic_backoff_start@@@ (3)'
   param :periodicbackoffend, :bsname => 'periodic_backoff_end', :name => '[periodicbackoffend]', :help => '@@@Text for periodic_backoff_end@@@ (15)'
   param :contentiontimeout, :bsname => 'contention_timeout', :name => '[contentiontimeout]', :help => 'Contention-based reservation timeout [0..255] (8)'
   param :startrangcode, :bsname => 'start_rangcode', :name => '[startrangcode]', :help => 'Initial value of code group of initial ranging. [0..255] (0)'
   param :initrangcode, :bsname => 'init_rangcode', :name => '[initrangcode]', :help => 'Number of initial CDMA ranging codes [0..255] (64)'
   param :periodicrangcode, :bsname => 'periodic_rangcode', :name => '[periodicrangcode]', :help => 'Number of periodic ranging CDMA codes available [0..255] (64)'
   param :bwrangcode, :bsname => 'bw_rangcode', :name => '[bwrangcode]', :help => 'Number of bandwidth request codes available. [0..255] (64)'
   param :horangcode, :bsname => 'ho_rangcode', :name => '[horangcode]', :help => 'Number of handover ranging codes. [0..255] (64)'
   param :feedbackstsymbol, :bsname => 'feedback_st_symbol', :name => '[feedbackstsymbol]', :help => '@@@Text for feedback_st_symbol@@@ (0)'
   param :feedbackstsubchan, :bsname => 'feedback_st_subchannel', :name => '[feedbackstsubchan]', :help => '@@@Text for feedback_st_subchannel@@@ (6)'
   param :feedbacknosymbol, :bsname => 'feedback_no_symbol', :name => '[feedbacknosymbol]', :help => '@@@Text for feedback_no_symbol@@@ (3)'
   param :feedbacknosubchan, :bsname => 'feedback_no_subchannel', :name => '[feedbacknosubchan]', :help => '@@@Text for feedback_no_subchannel@@@ (29)'
   param :bwreqstsymbol, :bsname => 'bwreq_st_symbol', :name => '[bwreqstsymbol]', :help => '@@@Text for bwreq_st_symbol@@@ (2)'
   param :bwreqstsubchan, :bsname => 'bwreq_st_subchannel', :name => '[bwreqstsubchan]', :help => '@@@Text for bwreq_st_subchannel@@@ (0)'
   param :bwreqnosymbol, :bsname => 'bwreq_no_symbol', :name => '[bwreqnosymbol]', :help => '@@@Text for bwreq_no_symbol@@@ (1)'
   param :bwreqnosubchan, :bsname => 'bwreq_no_subchannel', :name => '[bwreqnosubchan]', :help => '@@@Text for bwreq_no_subchannel@@@ (6)'
   param :initrangstsymbol, :bsname => 'initrang_st_symbol', :name => '[initrangstsymbol]', :help => '@@@Text for initrang_st_symbol@@@ (0)'
   param :initrangstsubchan, :bsname => 'initrang_st_subchannel', :name => '[initrangstsubchan]', :help => '@@@Text for initrang_st_subchannel@@@ (0)'
   param :initrangnosymbol, :bsname => 'initrang_no_symbol', :name => '[initrangnosymbol]', :help => '@@@Text for initrang_no_symbol@@@ (2)'
   param :initrangnosubchan, :bsname => 'initrang_no_subchannel', :name => '[initrangnosubchan]', :help => '@@@Text for initrang_no_subchannel@@@ (6)'
   param :harqackstsymbol, :bsname => 'harqack_st_symbol', :name => '[harqackstsymbol]', :help => '@@@Text for harqack_st_symbol@@@ (0)'
   param :harqackstsubchan, :bsname => 'harqack_st_subchannel', :name => '[harqackstsubchan]', :help => '@@@Text for harqack_st_subchannel@@@ (33)'
   param :harqacknosymbol, :bsname => 'harqack_no_symbol', :name => '[harqacknosymbol]', :help => '@@@Text for harqack_no_symbol@@@ (3)'
   param :harqacknosubchan, :bsname => 'harqack_no_subchannel', :name => '[harqacknosubchan]', :help => '@@@Text for harqack_no_subchannel@@@ (2)'
   param :initranginterval, :bsname => 'initrang_interval', :name => '[initranginterval]', :help => '@@@Text for initrang_interval@@@ (1)'
   param :defcinrave, :bsname => 'def_cinr_ave', :name => '[defcinrave]', :help => 'Default CINR averaging parameter on DCD messages. (0x03)'
   param :defrssiave, :bsname => 'def_rssi_ave', :name => '[defrssiave]', :help => 'Default RSSI averaging parameter on DCD messages. (0x00)'
   param :ttg, :bsname => 'ttg', :name => '[ttg]', :help => 'Transmit Receive transition gap (units: PS) (296)'
   param :rtg, :bsname => 'rtg', :name => '[rtg]', :help => 'Receive transmit transition gap (units: PS) (168)'
   param :agingtimeout, :bsname => 'aging_timeout', :name => '[agingtimeout]', :help => '@@@Text for aging_timeout@@@ (30)'
   param :odunoisefloor, :bsname => 'odu_noise_floor', :name => '[odunoisefloor]', :help => '@@@Text for odu_noise_floor@@@ (40)'
   param :pwradjustthres, :bsname => 'pwr_adjust_threshold', :name => '[pwradjustthres]', :help => '@@@Text for pwr_adjust_threshold@@@ (12)'
   param :ulpuscrotation, :bsname => 'ul_pusc_rotation', :name => '[ulpuscrotation]', :help => '@@@Text for ul_pusc_rotation@@@ (0)'
   param :fnrandseed, :bsname => 'fn_randseed', :name => '[fnrandseed]', :help => '@@@Text for fn_randseed@@@ (0)'
   param :sdumaxdelay, :bsname => 'sdu_max_delay', :name => '[sdumaxdelay]', :help => '@@@Text for sdu_max_delay@@@ (5000)'
   param :frameadjustthres, :bsname => 'frame_adjust_threshold', :name => '[frameadjustthres]', :help => '@@@Text for frame_adjust_threshold@@@ (500000)'
   param :framesyncmode, :bsname => 'framesync_mode', :name => '[framesyncmode]', :help => '@@@Text for framesync_mode@@@ (2)'
   param :rxinitialrangingmax, :bsname => 'rx_initial_ranging_max', :name => '[rxinitialrangingmax]', :help => '@@@Text for rx_initial_ranging_max@@@ (4)'
   param :rxhorangingmax, :bsname => 'rx_ho_ranging_max', :name => '[rxhorangingmax]', :help => '@@@Text for rx_ho_ranging_max@@@ (0)'
   param :rfcablelen, :bsname => 'rf_cable_len', :name => '[rfcablelen]', :help => '@@@Text for rf_cable_len@@@ (0)'
   param :odualmctrl, :bsname => 'odu_alm_control', :name => '[odualmctrl]', :help => '@@@Text for odu_alm_control@@@ (0x10000000)'
   param :timinggapoffset, :bsname => 'timing_gap_offset', :name => '[timinggapoffset]', :help => '@@@Text for timing_gap_offset@@@ (-748)'
   param :siiadvinterval, :bsname => 'siiadv_interval', :name => '[siiadvinterval]', :help => '@@@Text for siiadv_interval@@@ (10)'
   param :gmsenable, :bsname => 'gms_enable', :name => '[gmsenable]', :help => '@@@Text for gms_enable@@@ (0x06)'
   param :macvers, :bsname => 'mac_version', :name => '[macvers]', :help => '@@@Text for mac_version@@@ (6)'
   param :bcpietranscnt, :bsname => 'bcp_ie_transmit_count', :name => '[bcpietranscnt]', :help => '@@@Text for bcp_ie_transmit_count@@@ (117)'
   param :cqichbwreq, :bsname => 'cqich_bwreq', :name => '[cqichbwreq]', :help => '@@@Text for cqich_bwreq@@@ (1)'
   param :fairnessmode, :bsname => 'fairness_mode', :name => '[fairnessmode]', :help => '@@@Text for fairness_mode@@@ (1)'
   param :fairnesscountreset, :bsname => 'fairness_count_reset', :name => '[fairnesscountreset]', :help => '@@@Text for fairness_count_reset@@@ (2)'
end

class MPCService < BSPBase
   @name='mpc'
   @categoryName = 'mpc'
   @info='Set MEASUREMENT & POWER CONTROL parameters'
   param :ulcnoverride2, :bsname => 'ul_cn_override2', :name => '[ulcnoverride2]', :help => '@@@Text for ul_cn_override2@@@ (0x444423221234800C)'
   param :dlcnlist, :bsname => 'dl_cn_list', :name => '[dlcnlist]', :help => '@@@Text for dl_cn_list@@@ (0x08090A0E121617191B1C)'
   param :dlcnlist0, :bsname => 'dl_cn_list.0', :name => '[dlcnlist0]', :help => '@@@Text for dl_cn_list.0@@@ (8 (QPSK 1/2 x4))'
   param :dlcnlist1, :bsname => 'dl_cn_list.1', :name => '[dlcnlist1]', :help => '@@@Text for dl_cn_list.1@@@ (9 (QPSK 1/2 x2))'
   param :dlcnlist2, :bsname => 'dl_cn_list.2', :name => '[dlcnlist2]', :help => '@@@Text for dl_cn_list.2@@@ (10 (QPSK 1/2))'
   param :dlcnlist3, :bsname => 'dl_cn_list.3', :name => '[dlcnlist3]', :help => '@@@Text for dl_cn_list.3@@@ (14 (QPSK 3/4))'
   param :dlcnlist4, :bsname => 'dl_cn_list.4', :name => '[dlcnlist4]', :help => '@@@Text for dl_cn_list.4@@@ (18 (16QAM 1/2))'
   param :dlcnlist5, :bsname => 'dl_cn_list.5', :name => '[dlcnlist5]', :help => '@@@Text for dl_cn_list.5@@@ (22 (16QAM 3/4))'
   param :dlcnlist6, :bsname => 'dl_cn_list.6', :name => '[dlcnlist6]', :help => '@@@Text for dl_cn_list.6@@@ (23 (64QAM 1/2))'
   param :dlcnlist7, :bsname => 'dl_cn_list.7', :name => '[dlcnlist7]', :help => '@@@Text for dl_cn_list.7@@@ (25 (64QAM 2/3))'
   param :dlcnlist8, :bsname => 'dl_cn_list.8', :name => '[dlcnlist8]', :help => '@@@Text for dl_cn_list.8@@@ (27 (64QAM 3/4))'
   param :dlcnlist9, :bsname => 'dl_cn_list.9', :name => '[dlcnlist9]', :help => '@@@Text for dl_cn_list.9@@@ (28 (64QAM 5/6))'
   param :dlcnlista, :bsname => 'dl_cn_list_a', :name => '[dlcnlista]', :help => '@@@Text for dl_cn_list_a@@@ (0x08090A0E0F1417191B1C)'
   param :dlcnlista0, :bsname => 'dl_cn_list_a.0', :name => '[dlcnlista0]', :help => '@@@Text for dl_cn_list_a.0@@@ (8 (QPSK 1/2 x4))'
   param :dlcnlista1, :bsname => 'dl_cn_list_a.1', :name => '[dlcnlista1]', :help => '@@@Text for dl_cn_list_a.1@@@ (9 (QPSK 1/2 x2))'
   param :dlcnlista2, :bsname => 'dl_cn_list_a.2', :name => '[dlcnlista2]', :help => '@@@Text for dl_cn_list_a.2@@@ (10 (QPSK 1/2))'
   param :dlcnlista3, :bsname => 'dl_cn_list_a.3', :name => '[dlcnlista3]', :help => '@@@Text for dl_cn_list_a.3@@@ (14 (QPSK 3/4))'
   param :dlcnlista4, :bsname => 'dl_cn_list_a.4', :name => '[dlcnlista4]', :help => '@@@Text for dl_cn_list_a.4@@@ (15 (16QAM 1/2))'
   param :dlcnlista5, :bsname => 'dl_cn_list_a.5', :name => '[dlcnlista5]', :help => '@@@Text for dl_cn_list_a.5@@@ (20 (16QAM 3/4))'
   param :dlcnlista6, :bsname => 'dl_cn_list_a.6', :name => '[dlcnlista6]', :help => '@@@Text for dl_cn_list_a.6@@@ (23 (64QAM 1/2))'
   param :dlcnlista7, :bsname => 'dl_cn_list_a.7', :name => '[dlcnlista7]', :help => '@@@Text for dl_cn_list_a.7@@@ (25 (64QAM 2/3))'
   param :dlcnlista8, :bsname => 'dl_cn_list_a.8', :name => '[dlcnlista8]', :help => '@@@Text for dl_cn_list_a.8@@@ (27 (64QAM 3/4))'
   param :dlcnlista9, :bsname => 'dl_cn_list_a.9', :name => '[dlcnlista9]', :help => '@@@Text for dl_cn_list_a.9@@@ (28 (64QAM 5/6))'
   param :dlcnlistb, :bsname => 'dl_cn_list_b', :name => '[dlcnlistb]', :help => '@@@Text for dl_cn_list_b@@@ (0x08090A0E0F1417191B1C)'
   param :dlcnlistb0, :bsname => 'dl_cn_list_b.0', :name => '[dlcnlistb0]', :help => '@@@Text for dl_cn_list_b.0@@@ (8 (QPSK 1/2 x4))'
   param :dlcnlistb1, :bsname => 'dl_cn_list_b.1', :name => '[dlcnlistb1]', :help => '@@@Text for dl_cn_list_b.1@@@ (9 (QPSK 1/2 x2))'
   param :dlcnlistb2, :bsname => 'dl_cn_list_b.2', :name => '[dlcnlistb2]', :help => '@@@Text for dl_cn_list_b.2@@@ (10 (QPSK 1/2))'
   param :dlcnlistb3, :bsname => 'dl_cn_list_b.3', :name => '[dlcnlistb3]', :help => '@@@Text for dl_cn_list_b.3@@@ (14 (QPSK 3/4))'
   param :dlcnlistb4, :bsname => 'dl_cn_list_b.4', :name => '[dlcnlistb4]', :help => '@@@Text for dl_cn_list_b.4@@@ (15 (16QAM 1/2))'
   param :dlcnlistb5, :bsname => 'dl_cn_list_b.5', :name => '[dlcnlistb5]', :help => '@@@Text for dl_cn_list_b.5@@@ (20 (16QAM 3/4))'
   param :dlcnlistb6, :bsname => 'dl_cn_list_b.6', :name => '[dlcnlistb6]', :help => '@@@Text for dl_cn_list_b.6@@@ (23 (64QAM 1/2))'
   param :dlcnlistb7, :bsname => 'dl_cn_list_b.7', :name => '[dlcnlistb7]', :help => '@@@Text for dl_cn_list_b.7@@@ (25 (64QAM 2/3))'
   param :dlcnlistb8, :bsname => 'dl_cn_list_b.8', :name => '[dlcnlistb8]', :help => '@@@Text for dl_cn_list_b.8@@@ (27 (64QAM 3/4))'
   param :dlcnlistb9, :bsname => 'dl_cn_list_b.9', :name => '[dlcnlistb9]', :help => '@@@Text for dl_cn_list_b.9@@@ (28 (64QAM 5/6))'
   param :offsetbseirp, :bsname => 'offset_bseirp', :name => '[offsetbseirp]', :help => 'Offset value for open loop power control. (Units: db) [-32..31.75] (0)'
   param :nitxinterval, :bsname => 'ni_tx_interval', :name => '[nitxinterval]', :help => 'Time interval between N+I extended IE. (Units: frames) [0..255] (10)'
   param :pwconmode, :bsname => 'pwcon_mode', :name => '[pwconmode]', :help => '@@@Text for pwcon_mode@@@ (2)'
   param :openlpmodechg, :bsname => 'openloop_mode_chg', :name => '[openlpmodechg]', :help => '@@@Text for openloop_mode_chg@@@ (2)'
   param :clpoweradjust, :bsname => 'cl_power_adjust', :name => '[clpoweradjust]', :help => '@@@Text for cl_power_adjust@@@ (0)'
   param :cinrmeaspriority, :bsname => 'cinr_measure_priority', :name => '[cinrmeaspriority]', :help => '@@@Text for cinr_measure_priority@@@ (0x0104)'
   param :cinrreusefactor, :bsname => 'cinr_reuse_factor', :name => '[cinrreusefactor]', :help => '@@@Text for cinr_reuse_factor@@@ (0)'
   param :dlphyquality, :bsname => 'dl_phy_quality', :name => '[dlphyquality]', :help => '@@@Text for dl_phy_quality@@@ (0)'
   param :cqichrepinterval, :bsname => 'cqich_rep_interval', :name => '[cqichrepinterval]', :help => 'Report interval for CQICH. [0..3] (3)'
   param :cqichupdateinterval, :bsname => 'cqich_update_interval', :name => '[cqichupdateinterval]', :help => 'Update interval of transmitting CQICH allocation IE. (Units: frames) [40,80,160,320,640] (640)'
   param :mimofeedbkcycle, :bsname => 'MIMO_feedback_cycle', :name => '[mimofeedbkcycle]', :help => '@@@Text for MIMO_feedback_cycle@@@ (0)'
   param :reportfuncselect, :bsname => 'report_func_select', :name => '[reportfuncselect]', :help => '@@@Text for report_func_select@@@ (1)'
   param :cinrreportcontents, :bsname => 'cinr_report_contents', :name => '[cinrreportcontents]', :help => 'CINR reports content. (0)'
   param :reportintervalrep, :bsname => 'report_interval_rep', :name => '[reportintervalrep]', :help => 'Report interval of REP-REQ/RSP. (Units: frames) [0..255] (200)'
   param :reportintervalrssi, :bsname => 'report_interval_rssi', :name => '[reportintervalrssi]', :help => 'Report interval for REP-REQ/RSP. (Units: s) [0..60] (0)'
   param :pathlosscorrect, :bsname => 'pathloss_correct', :name => '[pathlosscorrect]', :help => '@@@Text for pathloss_correct@@@ (0)'
   param :rssiaverep, :bsname => 'rssi_ave_rep', :name => '[rssiaverep]', :help => '@@@Text for rssi_ave_rep@@@ (0x03)'
   param :ratectrlinterval, :bsname => 'rate_control_interval', :name => '[ratectrlinterval]', :help => 'Update interval for rate control. (Units: frames) [1..1024] (200)'
   param :matrixctrlinterval, :bsname => 'matrix_control_interval', :name => '[matrixctrlinterval]', :help => '@@@Text for matrix_control_interval@@@ (200)'
   param :rateupcount, :bsname => 'rate_up_count', :name => '[rateupcount]', :help => '@@@Text for rate_up_count@@@ (7)'
   param :ratedowncount, :bsname => 'rate_down_count', :name => '[ratedowncount]', :help => '@@@Text for rate_down_count@@@ (3)'
   param :clpowwaittime, :bsname => 'cl_power_waittime', :name => '[clpowwaittime]', :help => '@@@Text for cl_power_waittime@@@ (10)'
   param :powreportthres, :bsname => 'power_report_threshold', :name => '[powreportthres]', :help => 'Threshold of tx power report. (Units: db) [1..15] (15)'
   param :powreportduration, :bsname => 'power_report_duration', :name => '[powreportduration]', :help => 'Duration of tx power report. [1..15] (8)'
   param :alphapavg, :bsname => 'alpha_p_avg', :name => '[alphapavg]', :help => '@@@Text for alpha_p_avg@@@ (0)'
   param :pdusnwaittime, :bsname => 'pdu_sn_wait_time', :name => '[pdusnwaittime]', :help => '@@@Text for pdu_sn_wait_time@@@ (10)'
   param :gtb1int, :bsname => 'gtb1_int', :name => '[gtb1int]', :help => '@@@Text for gtb1_int@@@ (0)'
   param :gtb2int, :bsname => 'gtb2_int', :name => '[gtb2int]', :help => '@@@Text for gtb2_int@@@ (3800)'
   param :gtb4int, :bsname => 'gtb4_int', :name => '[gtb4int]', :help => '@@@Text for gtb4_int@@@ (2800)'
   param :rssicorrect, :bsname => 'rssi_correct', :name => '[rssicorrect]', :help => '@@@Text for rssi_correct@@@ (62)'
   param :cinrcorrect, :bsname => 'cinr_correct', :name => '[cinrcorrect]', :help => '@@@Text for cinr_correct@@@ (0)'
   param :niavgfactor, :bsname => 'ni_avg_factor', :name => '[niavgfactor]', :help => '@@@Text for ni_avg_factor@@@ (0)'
   param :laul, :bsname => 'la_ul', :name => '[laul]', :help => '@@@Text for la_ul@@@ (0)'
   param :ladl, :bsname => 'la_dl', :name => '[ladl]', :help => '@@@Text for la_dl@@@ (1)'
   param :hrpowmergin, :bsname => 'hr_power_mergin', :name => '[hrpowmergin]', :help => '@@@Text for hr_power_mergin@@@ (-24)'
   param :mngulburstpwroffset, :bsname => 'mng_ulburst_pwr_offset', :name => '[mngulburstpwroffset]', :help => '@@@Text for mng_ulburst_pwr_offset@@@ (0)'
   param :subchenable, :bsname => 'subch_enable', :name => '[subchenable]', :help => '@@@Text for subch_enable@@@ (0)'
   param :subchlimit, :bsname => 'subch_limit', :name => '[subchlimit]', :help => '@@@Text for subch_limit@@@ (0x04080402)'
   param :subchlimit0, :bsname => 'subch_limit.0', :name => '[subchlimit0]', :help => '@@@Text for subch_limit.0@@@ (4 (limit value before Enty))'
   param :subchlimit1, :bsname => 'subch_limit.1', :name => '[subchlimit1]', :help => '@@@Text for subch_limit.1@@@ (8 (limit value of class1 after Enty))'
   param :subchlimit2, :bsname => 'subch_limit.2', :name => '[subchlimit2]', :help => '@@@Text for subch_limit.2@@@ (4 (limit value of class2 after Enty))'
   param :subchlimit3, :bsname => 'subch_limit.3', :name => '[subchlimit3]', :help => '@@@Text for subch_limit.3@@@ (2 (limit value of class3 after Enty))'
   param :subchthres, :bsname => 'subch_threshold', :name => '[subchthres]', :help => '@@@Text for subch_threshold@@@ (0x54575A)'
   param :subchthres0, :bsname => 'subch_threshold.0', :name => '[subchthres0]', :help => '@@@Text for subch_threshold.0@@@ (84 (threshold of class1 after Enty))'
   param :subchthres1, :bsname => 'subch_threshold.1', :name => '[subchthres1]', :help => '@@@Text for subch_threshold.1@@@ (87 (threshold of class2 after Enty))'
   param :subchthres2, :bsname => 'subch_threshold.2', :name => '[subchthres2]', :help => '@@@Text for subch_threshold.2@@@ (90 (threshold of class3 after Enty))'
end

class MimoService < BSPBase
   @name='mimo'
   @categoryName = 'mimop'
   @info='Set MIMO parameters'
   param :mimo, :bsname => 'mimo', :name => '[mimo]', :help => 'MIMO on/off (0)'
   param :mimoul, :bsname => 'mimo_ul', :name => '[mimoul]', :help => '@@@Text for mimo_ul@@@ (0)'
   param :mimomatrix, :bsname => 'matrix', :name => '[mimomatrix]', :help => 'Preferred MIMO matrix - Matrix A. (0)'
end

class DebugService < BSPBase
   @name='debug'
   @categoryName='debug'
   @info='Set DEBUG parameters'
   param :debug27, :bsname => 'dbg_data27', :name => '[debug27]', :help => 'Debug variable 27 (-280)'
end

class MobileService < BSPBase
   @name='mobile'
   @categoryName='mobile'
   @info='Set MOBILE parameters'
   param :mobilefeatures, :bsname => 'mobility_features_supported', :name => '[mobilefeatures]', :help => 'Support handover/idle mode (1)'
   param :resrcretainflag, :bsname => 'resource_retain_flag', :name => '[ressrcretainflag]', :help => 'Flag to retain or release resource information of MS after handover. (1)'
   param :mshorettimer, :bsname => 'ms_ho_retransmission_timer', :name => '[mshorettimer]', :help => 'Timer until MS decides to retransmit MOB_MSHO-REQ. (Units: frames) [0..255] (100)'
   param :mobnbradvfragsize, :bsname => 'mob_nbr_adv_fragment_size', :name => '[mobnbradvfragsize]', :help => '@@@Text for mob_nbr_adv_fragment_size@@@ (50)'
   param :reportmode, :bsname => 'report_mode', :name => '[reportmode]', :help => 'Report mode for scanning results. (0)'
   param :reportperiod, :bsname => 'report_period', :name => '[reportperiod]', :help => 'Reporting period for scanning results (units: frames) [1..255] (100)'
   param :reportmetric, :bsname => 'report_metric', :name => '[reportmetric]', :help => 'Report metric for scanning results. (0x03)'
   param :hotypesupport, :bsname => 'ho_type_support', :name => '[hotypesupport]', :help => '@@@Text for ho_type_support@@@ (1)'
   param :assotypesupport, :bsname => 'association_type_support', :name => '[assotypesupport]', :help => 'Support for association type. (0x01)'
   param :homode, :bsname => 'ho_mode', :name => '[homode]', :help => '@@@Text for ho_mode@@@ (0)'
   param :trigval, :bsname => 'trigger_value', :name => '[trigval]', :help => 'Trig-condition trigger value [0.255] (2)'
   param :trigavgduration, :bsname => 'trigger_averaging_duration', :name => '[trigavgduration]', :help => 'DUration time for avergaing metric. (Units: frames) [0.255] (128)'
   param :pagingintervallen, :bsname => 'paging_interval_length', :name => '[pagingintervallen]', :help => 'Time duration for paging interal of BS. (Units: frames) (2)'
   param :trigtype, :bsname => 'trigger_type', :name => '[trigtype]', :help => 'Triggering metric type for SCN-REQ & SCN-REP. (0x00)'
   param :trigfunc, :bsname => 'trigger_function', :name => '[trigfunc]', :help => 'Triggering function type for SCN-REQ & SCN-REP (0x03)'
   param :unsolulgranthoindflag, :bsname => 'unsolicited_ul_grant_for_ho_ind_flag', :name => '[unsolulgranthoindflag]', :help => 'Support for unsolicitated UL grant or HO-IND (1)'
   param :hofastranging, :bsname => 'ho_fast_ranging', :name => '[hofastranging]', :help => 'Support for fast ranging. (0)'
   param :actiontimetbs, :bsname => 'action_time_tbs', :name => '[actiontimetbs]', :help => '@@@Text for action_time_tbs@@@ (2)'
   param :type55, :bsname => 't55', :name => '[type55]', :help => '@@@Text for t55@@@ (200)'
   param :scanduration, :bsname => 'scan_duration', :name => '[scanduration]', :help => '@@@Text for scan_duration@@@ (0)'
   param :interleavinginterval, :bsname => 'interleaving_interval', :name => '[interleavinginterval]', :help => '@@@Text for interleaving_interval@@@ (0)'
   param :scaniteration, :bsname => 'scan_iteration', :name => '[scaniteration]', :help => '@@@Text for scan_iteration@@@ (0)'
   param :trigvaluescnreq, :bsname => 'trigger_value_scn_req', :name => '[trigvaluescnreq]', :help => '@@@Text for trigger_value_scn_req@@@ (175)'
   param :trigavgdurationscnreq, :bsname => 'trigger_averaging_duration_scn_req', :name => '[trigavgdurationscnreq]', :help => '@@@Text for trigger_averaging_duration_scn_req@@@ (128)'
   param :trigtypescnreq, :bsname => 'trigger_type_scn_req', :name => '[trigtypescnreq]', :help => '@@@Text for trigger_type_scn_req@@@ (1)'
   param :trigfunctionscnreq, :bsname => 'trigger_function_scn_req', :name => '[trigfunctionscnreq]', :help => '@@@Text for trigger_function_scn_req@@@ (6)'
   param :trigvaluescnrep, :bsname => 'trigger_value_scn_rep', :name => '[trigvaluescnrep]', :help => '@@@Text for trigger_value_scn_rep@@@ (2)'
   param :trigavgdurationscnrep, :bsname => 'trigger_averaging_duration_scn_rep', :name => '[trigavgdurationscnrep]', :help => '@@@Text for trigger_averaging_duration_scn_rep@@@ (128)'
   param :trigtypescnrep, :bsname => 'trigger_type_scn_rep', :name => '[trigtypescnrep]', :help => '@@@Text for trigger_type_scn_rep@@@ (0)'
   param :trigfuncscnrep, :bsname => 'trigger_function_scn_rep', :name => '[trigfuncscnrep]', :help => '@@@Text for trigger_function_scn_rep@@@ (3)'
   param :reqduration, :bsname => 'req_duration', :name => '[reqduration]', :help => 'Expiration time for initiation of MS Idle mode in DREG-REQ (Units: frames) [0..255] (10)'
   param :cidupdateswitch, :bsname => 'cid_update_switch', :name => '[cidupdateswitch]', :help => 'Support for CID update. (0)'
   param :faindex, :bsname => 'fa_index', :name => '[faindex]', :help => '@@@Text for fa_index@@@ (0)'
   param :mobnbradvinterval, :bsname => 'mob_nbr_adv_interval', :name => '[mobnbradvinterval]', :help => 'Interval of MOB_NBR-ADV messages. [0..30] (10)'
   param :pagingretrycount, :bsname => 'paging_retry_count', :name => '[pagingretrycount]', :help => 'Max number of retransmission MOB_PAG-ADV message. (3)'
   param :mngresourceholdingtimer, :bsname => 'mng_resource_holding_timer', :name => '[mngresourceholdingtimer]', :help => 'Time to maintain connection information after BS transmits DREG-CMD. (Units: 100ms) [0..65535] (5)'
   param :dregcmdretrycount, :bsname => 'dreg_command_retry_count', :name => '[dregcmdretrycount]', :help => 'Max number of retransmissions in DREQ-CMD. (3)'
   param :type46, :bsname => 't46', :name => '[type46]', :help => '@@@Text for t46@@@ (250)'
   param :resourceretaintime, :bsname => 'resource_retain_time', :name => '[resourceretaintime]', :help => 'Duration for retaining resource information af MS handover. (Units: ms) [0..65335] (0x000A)'
   param :sysresourceretaintime, :bsname => 'system_resource_retain_time', :name => '[sysresourceretaintime]', :help => '@@@Text for system_resource_retain_time@@@ (300)'
   param :targetbsselection, :bsname => 'target_bs_selection', :name => '[targetbsselection]', :help => '@@@Text for target_bs_selection@@@ (0)'
   param :recommendedneighborbsid, :bsname => 'recommended_neighbor_bsid', :name => '[recommendedneighborbsid]', :help => '@@@Text for recommended_neighbor_bsid@@@ (0x000000000000)'
   param :dlcinrthrescqich, :bsname => 'dlcinr_threshold_cqich', :name => '[dlcinrthrescqich]', :help => '@@@Text for dlcinr_threshold_cqich@@@ (0)'
   param :dlcinrmeanthres, :bsname => 'dlcinr_mean_threshold', :name => '[dlcinrmeanthres]', :help => '@@@Text for dlcinr_mean_threshold@@@ (12)'
   param :pwrsavingclasscap, :bsname => 'power_saving_class_capability', :name => '[pwrsavingclasscap]', :help => '@@@Text for power_saving_class_capability@@@ (1)'
   param :trfindrequired, :bsname => 'trf_ind_required', :name => '[trfindrequired]', :help => '@@@Text for trf_ind_required@@@ (1)'
   param :trftrigwakenflag, :bsname => 'traffic_triggered_wakening_flag', :name => '[trftrigwakenflag]', :help => '@@@Text for traffic_triggered_wakening_flag@@@ (0)'
   param :trfindswitch, :bsname => 'trf_ind_switch', :name => '[trfindswitch]', :help => '@@@Text for trf_ind_switch@@@ (1)'
   param :commmonitortmr, :bsname => 'communication_monitor_timer', :name => '[commmonitortmr]', :help => '@@@Text for communication_monitor_timer@@@ (300)'
   param :mobpagadvtranscnt, :bsname => 'mob_pag_adv_transmit_count', :name => '[mobpagadvtranscnt]', :help => 'Time duration margin for transmission timing in MOB_PAG-ADV. (Units: frames) [0.255] (2)'
end

class SecurityService < BSPBase
   @name='security'
   @categoryName='security'
   @info='Set SECURITY parameters'
   param :pkmflowcontrol, :bsname => 'pkm_flow_control', :name => '[pkmflowcontrol]', :help => '@@@Text for pkm_flow_control@@@ (0)'
   param :maxsecurityasso, :bsname => 'max_security_association', :name => '[maxsecurityasso]', :help => '@@@Text for max_security_association@@@ (1)'
   param :pkmversionsupport, :bsname => 'pkm_version_support', :name => '[pkmversionsupport]', :help => '@@@Text for pkm_version_support@@@ (0x02)'
   param :tekkeylifetime, :bsname => 'tek_key_lifetime', :name => '[tekkeylifetime]', :help => 'Lifetime of a newly assigned TEK. (Units: s) [60..604800] (3600)'
   param :cryptosuite, :bsname => 'cryptographic_suite', :name => '[cryptosuite]', :help => '@@@Text for cryptographic_suite@@@ (0x00020104)'
   param :authgracetime, :bsname => 'auth_grace_time', :name => '[authgracetime]', :help => 'Grace time before MS acquires another authorization key. (Units: s) [70..604800] (70)'
   param :tekgracetime, :bsname => 'tek_grace_time', :name => '[tekgracetime]', :help => 'Grace time for TEK. (Units: 600) [10..3600] (600)'
   param :sachallengetmr, :bsname => 'sa_challenge_timer', :name => '[sachallengetmr]', :help => 'Timeout value for SA-TEK challenge retranmission. (Units: 100ms) [5..20] (10)'
   param :sachallengemaxresends, :bsname => 'sa_challenge_max_resends', :name => '[sachallengemaxresends]', :help => 'Max number of SA-TEK challenge transmissions. (3)'
end
